---
title: "Exercise 0"
output: html_notebook
---

Goals:  

- Create a R Notebook
- Import a dataset using `reader::read_csv()`

> ANSWER can be found in exercise_00_answers.Rmd file

## Directions

For the workshop, we've prebuilt a data set that has information about menus in Duke's Brodhead Center from three restaurants.  

1. From the File menu, open a New R Notebook:  `File > New File > R Notebook`
2. Add a code chunk at/around line 20.  (Hint: *Ctrl+Alt+I*)
3. Load the `tidyverse` library package in that code-chunk.  Run that code chunk
4. Insert another new code chunks and follow the steps in below.


## Exercise: Data Structures & Vector Types

5. Using what you've seen in class, if `data/brodheadCenter.csv` is a CSV (comma separated values) file, how would you load the file into a new object called `brodhead`?

6. Make a code chunk and display your new `brodhead` data frame?

7.  `starwars` is an on-board dataset that comes with the tidyverse.  Make a new code chunk and display that data.  

8.  Copy and paste the following code into a new code chunk in your new file.  

```{r}
starwars %>% 
  ggplot(aes(fct_infreq(hair_color))) + 
  geom_bar() + 
  ggtitle("Hair Color Frequency of Star Wars Characters")
```

BONUS

9. Take a look at the structure of the `brodhead` object.
    - How many observations (rows) are there?
    - How many variables (columns) are there?
    - How many of the variables are numeric data?
    
    HINT:  You can use the `glimpse() function`

> ANSWER can be found in answers_00.Rmd file
