---
title: "Exercise 01 - dplyr -- data wrangling"
---

## Goals:  

Use dplyr functions to wrangle data

In this exercise you'll practice the `dplyr` verbs (i.e. *functions*) mentioned in the demonstration.

- `arrange()`
- `filter()`
- `mutate()`
- `select()`
- `count()`

## Directions

### Setup

We've prebuilt a data set that has information about menus in Duke's Brodhead Center (dining hall) from three restaurants.  Create a new R Notebook, load the *tidyverse* package, and **load the dining hall dataset**, *as a tibble*.  The broadhead dataset is a CSV file in the `data` directory.

1. From the File menu, open a New R Notebook:  `File > New File > R Notebook`
2. Reading the preloaded directions in your new script, add a code chunk at/around line 20.  (Hint: *Ctrl+Alt+I*)
3. Load the `tidyverse` package.  In that code-chunk, type: `library(tidyverse)` and **run the code chunk**.
4. Insert a code chunk and load the practice data from the `data` directory:  

    - Remember to assign the imported data to an object name, e.g. "brodhead"
    
**After loading a library package and importing data from above**
    
Now you are ready to make new code chunks and follow the steps in Exercise 1 (below).

> Remember:  Answers can be found in the answer_01.Rmd file


### Exercise:  Data Wrangling

All of the following questions are based on the sample of restaurants represented in the dataset which is accurate as of September 2, 2016.

1. Which restaurant has the lowest cost item and what is the item?

2. Which restaurant has the most expensive item(s)?  What are those item(s)?

3. At the Brodhead Center, how many of the entrees (found in the `menuType` variable) cost eight dollars?

4. The head of Duke dining is considering reducing prices at the Brodhead Center. Using what we've learned in class, write code that will calculate a new variable (`halfPrice`) that contains items at half price.

5. How many entrees are in the dataset (`menuType` variable)? How many desserts 
    
## Answers

See [the answers](answers.Rmd) to the above section

## Quiz

Take the [interactive quiz](https://libjohn.shinyapps.io/intro2r_quizzes/#section-data-wrangling-with-dplyr)